
  CREATE TABLE "HZQGAS"."GAS_REPORT_CLEAR" 
   (	"CLEAR_ID" VARCHAR2(64 BYTE) DEFAULT NULL NOT NULL ENABLE, 
	"TRADE_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CLEAR_DATE" DATE, 
	"CLEAR_CUR_MONEY" NUMBER(20,2) DEFAULT 0.00, 
	"REPORT_YEAR" NUMBER(10,0), 
	"REPORT_MONTH" NUMBER(10,0), 
	"CLEAR_PREV_MONEY" NUMBER(20,2) DEFAULT 0.00, 
	"NEW_ARREARS_MONEY" NUMBER(20,2) DEFAULT 0.00, 
	"CUSTOMER_CODE" VARCHAR2(20 BYTE), 
	"CLEAR_ALL_MONEY" NUMBER(20,2), 
	"TRADE_DATE" DATE, 
	 CONSTRAINT "GAS_REPORT_CLEAR_PK" PRIMARY KEY ("CLEAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HZQGAS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HZQGAS" ;
 

   COMMENT ON COLUMN "HZQGAS"."GAS_REPORT_CLEAR"."CLEAR_DATE" IS '清欠时间';
 
   COMMENT ON COLUMN "HZQGAS"."GAS_REPORT_CLEAR"."CLEAR_CUR_MONEY" IS '清本年';
 
   COMMENT ON COLUMN "HZQGAS"."GAS_REPORT_CLEAR"."CLEAR_PREV_MONEY" IS '清陈欠';
 
   COMMENT ON COLUMN "HZQGAS"."GAS_REPORT_CLEAR"."NEW_ARREARS_MONEY" IS '新增欠费';
 
   COMMENT ON COLUMN "HZQGAS"."GAS_REPORT_CLEAR"."CLEAR_ALL_MONEY" IS '每次清欠总费 ';
 
   COMMENT ON COLUMN "HZQGAS"."GAS_REPORT_CLEAR"."TRADE_DATE" IS '交易时间';
 
